- name: Install Nginx
  hosts: WEB
  become: true
  tasks:
    - name: Install the latest version of Apache
      ansible.builtin.yum:
        name: httpd
        state: latest

    - name: Make sure a service unit is running
      ansible.builtin.systemd:
        state: started
        name: httpd
        enable: yes

- name: Installing Nginx1
  hosts: WEB
  become: true
  roles:
    - sample


